Change environment variables to use getenv.
silverstripe/silverstripe-dynamodb pull request #28
Opened 2017-08-11 04:06 UTC by ichaber

Changed the dynamodb module to use getenv so it can be used with SilverStripe 4

2017-08-11 11:55 UTC, dhensby approved these changes

2017-08-11 11:58 UTC, Firesphere commented
Difference is the formatting, which I didn't and Charlie did :D It's yours Charlie, you now own this module :P

2017-08-11 12:02 UTC, Firesphere commented on code/Model/DynamoDbSession.php
> +            return $AWS_DYNAMODB_SESSION_LIFETIME;
As discussed, it would be good if we could add some tests, but that might not be part of this PR

2017-08-13 21:05 UTC, halkyon commented on code/Model/DynamoDbSession.php
> +            $AWS_REGION_NAME = getenv('AWS_REGION_NAME');
Can you please clean up the variable names? The standard is `$awsRegionName` and such :)

2017-09-01 13:04 UTC, dhensby commented
bump

2017-10-18 21:25 UTC, stojg requested changes
Awaiting variable name change to code standard

2017-10-24 00:49 UTC, tractorcow requested changes

2017-10-24 00:49 UTC, tractorcow commented on code/Model/DynamoDbSession.php
> +        $AWS_DYNAMODB_SESSION_TABLE = getenv('AWS_DYNAMODB_SESSION_TABLE');
Sorry, but given recent API changes these need updating again.

Please use `SilverStripe\Core\Environment::getEnv()` instead.

2017-11-17 01:51 UTC, sminnee commented
Could someone please pull this one over the line?

2017-11-19 21:19 UTC, tractorcow commented
Feedback implemented at https://github.com/silverstripe/silverstripe-dynamodb/pull/30 (except tests)

2017-11-20 00:07 UTC, chillu commented
Talked to Charlie, replaced with https://github.com/silverstripe/silverstripe-dynamodb/pull/30

2017-11-20 00:07 UTC, closed without merging