binary safe session persistence
silverstripe/silverstripe-dynamodb pull request #33
Opened 2019-06-27 03:10 UTC by dnsl48

FIX AWS SDK PHP DynamoDb StandardSessionConnection handles serialized sessions as strings, which is not binary safe

fixes #32

2019-06-27 03:29 UTC, chillu requested changes

2019-06-27 03:29 UTC, chillu commented on code/DynamoDbClient.php
> +    private $sessionTable;
Type hints and docs please.

2019-07-01 03:23 UTC, dnsl48 commented
ready for a review

2019-07-01 23:23 UTC, chillu commented
Works as advertised :) Was particularly interested in the transition of existing sessions once the new functionality is used. Tested with DynamoDB Local, see https://github.com/silverstripe/silverstripe-dynamodb/pull/34.

Add the following code to `PageController->init()`:

```php
$this->getRequest()->getSession()->set('foo', 'bar');
```

Use master branch. Visit `/?flush=1`. Observe session being created with string values:

```
aws dynamodb scan --table-name mysession --endpoint-url http://localhost:8000
{
    "Count": 1, 
    "Items": [
        {
            "expires": {
                "N": "1562024548"
            }, 
            "data": {
                "S": "foo|s:3:\"bar\";HTTP_USER_AGENT|s:121:\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36\";"
            }, 
            "id": {
                "S": "PHPSESSID_7r6bcvrbb1cu8anch8img3lerp"
            }
        }
    ], 
    "ScannedCount": 1, 
    "ConsumedCapacity": null
}
```

Switch to PR branch. Visit `/?flush=1` (in same browser session). Observe session data in DynamoDB hasn't changed.

Read out existing session value (in controller or elsewhere):

```php
var_dump($this->getRequest()->getSession()->get('foo'));die();
```

Change the `PageController->init()` to a different session value:

```php
$this->getRequest()->getSession()->set('foo', 'baz');
```

Visit `/?flush=1`. Observe session data changed to binary:

```
{
    "Count": 1, 
    "Items": [
        {
            "expires": {
                "N": "1562024689"
            }, 
            "data": {
                "B": "Zm9vfHM6MzoiYmF6IjtIVFRQX1VTRVJfQUdFTlR8czoxMjE6Ik1vemlsbGEvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE0XzUpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS83NS4wLjM3NzAuMTAwIFNhZmFyaS81MzcuMzYiOw=="
            }, 
            "id": {
                "S": "PHPSESSID_7r6bcvrbb1cu8anch8img3lerp"
            }
        }
    ], 
    "ScannedCount": 1, 
    "ConsumedCapacity": null
}
```

Read out session value, observe new value:

```php
var_dump($this->getRequest()->getSession()->get('foo'));die();
```

2019-07-01 23:25 UTC, chillu approved these changes

2019-07-01 23:25 UTC, merged